# NumPy Basics

In [ ]:
# importing the Numpy as a python code
import numpy as np

In [ ]:
# numpy code look like bellow described
a = np.array([[1, 2, 3], [4, 5, 6]])
# lets print the array
print(a)
# lets see the sphape of the array i.e the number of rows and columns
print(f"The shape of the array is {a.shape}")

[[1 2 3]
 [4 5 6]]
The shape of the array is (2, 3)


# Limitations of Numpy Array

In [ ]:
# we can make any dimensional array using numpy array. It has some limitations. lets see them...
# 1) All elements of the array must be the of same data type.
# 2) Once created, the total size of the array can't be changed.
# 3) The shape of the array must be rectangular, not jagged.

# Array fundamentals

In [ ]:
# One way to initialize array is just like Python list

b = np.array([1, 2, 3, 4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

Accessing the array element

In [ ]:
# The array elements can be accessed by using the array index
print(b[0])

1


Like the original list, the numpy array is mutable

In [ ]:
print(b)
b[0] = 10
print(b)

[1 2 3 4 5 6]
[10  2  3  4  5  6]


# Array slicing

In [ ]:
# when we slice an array we get the view of the orginal array
# where as if we slice the list of python we a new object is made and it refers to the new object

In [ ]:
print(b)

[10  2  3  4  5  6]


In [ ]:
b[:4]

array([10,  2,  3,  4])

In [ ]:
original_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
sliced_list = original_list[2:-2]
# you can write this like
# slice_list = original_list[2:7]
print("The original list is : ",original_list )
print("The sliced list is : ",sliced_list)

The original list is :  [1, 2, 3, 4, 5, 6, 7, 8, 9]
The sliced list is :  [3, 4, 5, 6, 7]


In [ ]:
sliced_list[1] = 100
print("The original list is : ", original_list)
print("The sliced list is : ", sliced_list)

The original list is :  [1, 2, 3, 4, 5, 6, 7, 8, 9]
The sliced list is :  [3, 100, 5, 6, 7]


In [ ]:
# As there is no impact on the original list while changing the sliced_list.
# Therefore we can say that a new object is was made.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
new_array = original_array[1:-1]
print("The original array is : ",original_array)
print("The sliced array is : ", new_array)

The original array is :  [1 2 3 4 5]
The sliced array is :  [2 3 4]


In [ ]:
new_array[0] = 10
print("The original array is : ", original_array)
print("The sliced array is : ", new_array)

The original array is :  [ 1 10  3  4  5]
The sliced array is :  [10  3  4]


In [ ]:
# As we can see that on changing the sliced array element there is the change in the original array
# Therefore we can say that on slicing the array, we just get a view of the original array not a new array is made.

# Multi dimensional array

In [ ]:
#Two or more dimensional array can be initialized using python nested sequence

c = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# sometimes dimension of an array is referred to as "axis". This is for avoiding the confusion
# between the array dimension and the dimension of the data represented by the array.

# **Accessing the array elements from a multidimensional array**

In [ ]:
c[1,2]

6

# Some standard definations
1.   **Sclar** - zero dimensional array.
2.   **vector**- one dimensional array.
3.   **matrix** - two dimensional array.
4.   **tensor** - N dimensional array.(N>2)









# Array Attributes

In this section we are going to discuss about `ndim`, `shape`, `size`, and `dtype`.

In [ ]:
# The number of dimension of the array is contained in the ndim attribute.
print("The dimension of the array a is : ", a.ndim)
print("The dimension of the array b is : ", b.ndim)

The dimension of the array a is :  2
The dimension of the array b is :  1


In [ ]:
# The shape of an array is non-negative tuple which represents the number of elements in each dimension
print("The shape of the array a is : ",a.shape)
print("The shape of the array b is : ",b.shape)

The shape of the array a is :  (2, 3)
The shape of the array b is :  (6,)


In [ ]:
len(a.shape) == a.ndim

True

In [ ]:
# The fixed total number of element in the array is shown by size attribute
a.size

6

In [ ]:
import math
a.size == math.prod(a.shape)

True

In [ ]:
# Array in numpy is homogeneous in nature. They can contain only the data of same data type.
# The datatype of the array element is contained in dtype arrtribute.
print(a.dtype)
print("here int is for integer{number} and 64 is for 64bits of data")

int64
here int is for integer{number} and 64 is for 64bits of data


# Creation of Basic Array