# **Numpy Tutorial**

# Numpy :

Numpy is a general purpose array processing package.It provides a high performance multidimensional array object, and tools for working with those arrays.It is the fundamental package for scientific computing with python.

# What is an Array ?

Array is an data structure which stores values of same data type. In python this is the main difference between Array and list.While python lists can have contain the values of different data types, but arrays can have only contain the values of same data type only.

In [2]:
# import the library
import numpy as np;

In [3]:
# making a list and converting the list into the array.
lst1 = [1, 2, 3, 4]
# now converting the list into the array
np.array(lst1)

array([1, 2, 3, 4])

In [11]:
lst2 = ["sougata", 2005, "2nd"]
array1 = np.array(lst2)
array1

array(['sougata', '2005', '2nd'], dtype='<U21')

In [10]:
print(type(lst2))
print(type(array1))
print(array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
<U21


here we can see that though the `lst2` contains the value of different data type but it is converted to an array.In NumPy, when we create an array from a Python list that contains mixed data types (e.g., strings and integers), NumPy automatically converts the list into an array with a common data type. This is because NumPy arrays are designed to store elements of the same data type (homogeneous), and when the input list has mixed data types, NumPy will attempt to find a common data type that can accommodate all elements.



1.   `lst2` is a list with mixed data types: a string "sougata", an integer 2005, and a string "2nd".

2.   NumPy attempts to convert this list into an array. Since the list contains both strings and integers, NumPy automatically promotes the entire array to the string data type because strings can accommodate both other strings and integers when converted to a string format.


3.  The resulting array will contain strings for all elements, and the integer 2005 will be converted to "2005" (a string).

The dtype=`"<U21"` indicates that the data type is a Unicode string with a maximum length of 21 characters.






In [12]:
lst = [1, 2, 3, 4]
arr = np.array(lst)

In [13]:
type(arr)

numpy.ndarray

In [14]:
# in built function of numpy array to get to know the shape of the array.
arr.shape

(4,)

In [18]:
# making two dimensional array i.e multiple row and column
lst1 = [1, 2, 3, 4, 5]
lst2 = [2, 3, 4, 5, 6]
lst3 = [3, 4, 5, 6, 7]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [19]:
arr1.shape

(3, 5)

In [20]:
# indexing (retriving the values)
arr

array([1, 2, 3, 4])

In [21]:
arr[3]

4

In [22]:
# changing the value of array element using indexing
arr[3] = 5
arr[3]

5

In [23]:
# retriving the array elements present onwards a specific index
arr[1:]

array([2, 3, 5])

In [24]:
arr[1:3]

array([2, 3])

In [25]:
# taking all the elements except the last element
arr[:-1]

array([1, 2, 3])

In [26]:
arr[:-2]

array([1, 2])

i.e this syntax means that retrive the elements of the array from starting to the specified index, but indexing is done from last.

In [27]:
# retriving order of the elements and the sequence
arr[::]

array([1, 2, 3, 5])

In [28]:
arr[::-1]

array([5, 3, 2, 1])

In [29]:
# arr[staring_index:ending_index:difference(or, order)]
arr[::-2]

array([5, 2])

In [30]:
arr[::2]

array([1, 3])

In [31]:
arr[1::2]

array([2, 5])

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [33]:
# for retriving the datas of a two dimensional array is
#  array_name[row_property,column_property]


arr1[:,1]

array([2, 3, 4])

In [34]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [35]:
arr1[1:,-2:]

array([[5, 6],
       [6, 7]])

In [37]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [38]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [39]:
arr1[:,3:].shape

(3, 2)

In [41]:
# assignment question
arr1[:,::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

# EDA (Exploratory Data Analysis)

 EDA is a mothod used by data scientists to analyze and investigate data sets

In [42]:
arr

array([1, 2, 3, 5])

In [43]:
arr<2

array([ True, False, False, False])

In [45]:
arr[arr<2]

array([1])

In [46]:
arr[arr>2]

array([3, 5])

# Reshaping the Array

In [47]:
arr1.shape

(3, 5)

In [48]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [51]:
arr1.reshape(5, 3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [50]:
# note while reshaping, total number of elements must be same
arr1.reshape(5, 4)

ValueError: cannot reshape array of size 15 into shape (5,4)

## Array mechanism

In [52]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# syntax for arange inbuilt function
# np.arrang(staring_element, ending_element, order (or difference))
np.arange(2,20,5)

array([ 2,  7, 12, 17])

In [55]:
np.arange(1,20,1).shape

(19,)

In [59]:
brr = np.arange(1, 20, 2)
brr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [60]:
brr.size

10

In [61]:
brr.reshape(2, 5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [62]:
brr.reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [63]:
brr.shape

(10,)

# Array multiplication

for the array multiplication it is not like the matrix multiplication, here just the element of same indices gets multiplied.

In [64]:
arr

array([1, 2, 3, 5])

In [65]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [66]:
arr * arr

array([ 1,  4,  9, 25])

In [68]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [70]:
# dimensions of the arrays must be same for the multiplication, this is known as the array broadcasting.
arr * arr1

ValueError: operands could not be broadcast together with shapes (4,) (3,5) 

# Inbulit specific Arrays

In [71]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
for i in range(1, 10):
  print(np.random.randint(2, 100), end = ", ")

81, 95, 95, 82, 77, 30, 98, 80, 57, 

In [81]:
np.random.randint(2, 50, 6)

array([ 9, 23, 11, 13, 41, 38])

In [82]:
np.random.randint(9, 30, 25).reshape(5, 5)

array([[11, 28, 17, 15, 15],
       [15, 22, 19, 27, 20],
       [22, 16, 23, 12, 24],
       [29, 13, 10, 29, 19],
       [23, 27, 17, 22, 20]])

In [86]:
# syntax ===>
# np.random.randing(low{inclusive}, high{exclusive}, size(m, n, ..))
np.random.randint(1, size =10)
# by default, low value is zero and high value is taken as 1 which is exclusive, therefore we only 0 is the array element

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
np.random.randint(2, size = 10)

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0])

In [89]:
# Generate a 2 x 4 array of ints between 0 and 4, inclusive:
np.random.randint(0,5,(2,4))

array([[1, 3, 4, 3],
       [3, 2, 3, 1]])

In [90]:
np.random.randint(low = 0, high = 5, size = (2, 4))

array([[3, 1, 3, 2],
       [4, 0, 3, 0]])

In [91]:
np.random.randint(5, size = (2, 4))

array([[4, 4, 0, 0],
       [0, 3, 4, 1]])